name: Deploy Angular App to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular App
        run: |
          cd Web_UI  # Change directory to your Angular app
          npm install --f
          ng build --prod

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: deltalpg
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
